# Generated by Django 4.2.3 on 2023-07-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='books')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
            ],
        ),
    ]
