# Generated by Django 4.2.3 on 2023-07-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default=0, upload_to='books'),
            preserve_default=False,
        ),
    ]
